twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        app_name: '%env(APP_NAME)%'
        app_email_name: '%env(MAILER_NAME)%'
        app_email_address: '%env(MAILER_ADDRESS)%'

when@test:
    twig:
        strict_variables: true
